--- 
title: "Text Analysis with R"
author: "Claudia Engel, Scott Bailey"
date: "Last updated: `r format(Sys.time(), '%B %d, %Y')`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: cengel/R-text-analysis
description: "Workshop materials for Text Analysis in R"
geometry: "left=3cm,right=1cm,top=2cm,bottom=2cm"
---


# Prerequisites {-}

- You should have a **basic knowledge** of R, and be familiar with the topics covered in the [Introduction to R](https://cengel.github.io/R-intro/).

- It is also recommended you have a **recent** version of [R](https://cran.r-project.org/) and [RStudio](https://www.rstudio.com/) installed. 

- Packages needed:
  - `tidyverse`
  - `tidytext`
  - `readtext`
  - `sotu`
  - `SnowballC`
  - `widyr`
  - `igraph`
  - `ggraph`
  - `tm`

Make sure that you not only install, but also load the packages, to confirm the respective versions get along with your R version.

## References  {-}

Feinerer, I., Hornik, K., and Meyer, D. (2008). [Text Mining Infrastructure in R](http://dx.doi.org/10.18637/jss.v025.i05). Journal of Statistical Software, 25(5), 1 - 54. doi: dx.doi.org/10.18637/jss.v025.i05

Gries, Stefan Thomas, 2009: [Quantitative Corpus Linguistics with R: A Practical Introduction](http://www.stgries.info/research/qclwr/qclwr.html). Routledge.

Silge, J and D. Robinson, 2017: [Text Mining with R: A Tidy Approach](http://tidytextmining.com/)

Niekler, A. and G. Wiedemann 2020: [Text mining in R for the social sciences and digital humanities](https://tm4ss.github.io/docs/index.html)

Kasper Welbers, Wouter Van Atteveldt & Kenneth Benoit (2017) [Text Analysis in R](https://doi.org/10.1080/19312458.2017.1387238). Communication Methods and Measures, 11:4, 245-265 doi: 10.1080/19312458.2017.1387238

Scott Chamberlain (2019). [fulltext: Full Text of 'Scholarly' Articles Across Many Data Sources](https://books.ropensci.org/fulltext/)

[CRAN Task View: Natural Language Processing](https://CRAN.R-project.org/view=NaturalLanguageProcessing)
