<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Chapter 1 Preparing Textual Data | Text Analysis with R</title>
  <meta name="description" content="Workshop materials for Text Analysis in R">
  <meta name="generator" content="bookdown  and GitBook 2.6.7">

  <meta property="og:title" content="Chapter 1 Preparing Textual Data | Text Analysis with R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Workshop materials for Text Analysis in R" />
  <meta name="github-repo" content="cengel/R-text-analysis" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 1 Preparing Textual Data | Text Analysis with R" />
  
  <meta name="twitter:description" content="Workshop materials for Text Analysis in R" />
  

<meta name="author" content="Claudia Engel, Scott Bailey">



  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="index.html">
<link rel="next" href="textanalysis.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Text Analysis with R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Prerequisites</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#references"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="textprep.html"><a href="textprep.html"><i class="fa fa-check"></i><b>1</b> Preparing Textual Data</a><ul>
<li class="chapter" data-level="1.1" data-path="textprep.html"><a href="textprep.html#reading-text-into-r"><i class="fa fa-check"></i><b>1.1</b> Reading text into R</a></li>
<li class="chapter" data-level="1.2" data-path="textprep.html"><a href="textprep.html#string-operations"><i class="fa fa-check"></i><b>1.2</b> String operations</a></li>
<li class="chapter" data-level="1.3" data-path="textprep.html"><a href="textprep.html#tokenize-lowercase"><i class="fa fa-check"></i><b>1.3</b> Tokenize, lowercase</a></li>
<li class="chapter" data-level="1.4" data-path="textprep.html"><a href="textprep.html#stopwords"><i class="fa fa-check"></i><b>1.4</b> Stopwords</a></li>
<li class="chapter" data-level="1.5" data-path="textprep.html"><a href="textprep.html#word-stemming"><i class="fa fa-check"></i><b>1.5</b> Word Stemming</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="textanalysis.html"><a href="textanalysis.html"><i class="fa fa-check"></i><b>2</b> Analyzing Texts</a><ul>
<li class="chapter" data-level="2.1" data-path="textanalysis.html"><a href="textanalysis.html#frequencies"><i class="fa fa-check"></i><b>2.1</b> Frequencies</a></li>
<li class="chapter" data-level="2.2" data-path="textanalysis.html"><a href="textanalysis.html#term-frequency"><i class="fa fa-check"></i><b>2.2</b> Term frequency</a></li>
<li class="chapter" data-level="2.3" data-path="textanalysis.html"><a href="textanalysis.html#tf-idf"><i class="fa fa-check"></i><b>2.3</b> Tf-idf</a></li>
<li class="chapter" data-level="2.4" data-path="textanalysis.html"><a href="textanalysis.html#n-grams"><i class="fa fa-check"></i><b>2.4</b> N-Grams</a></li>
<li class="chapter" data-level="2.5" data-path="textanalysis.html"><a href="textanalysis.html#co-occurrence"><i class="fa fa-check"></i><b>2.5</b> Co-occurrence</a></li>
<li class="chapter" data-level="2.6" data-path="textanalysis.html"><a href="textanalysis.html#document-term-matrix"><i class="fa fa-check"></i><b>2.6</b> Document-Term Matrix</a></li>
<li class="chapter" data-level="2.7" data-path="textanalysis.html"><a href="textanalysis.html#sentiment-analysis"><i class="fa fa-check"></i><b>2.7</b> Sentiment analysis</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Text Analysis with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="textprep" class="section level1">
<h1><span class="header-section-number">Chapter 1</span> Preparing Textual Data</h1>
<blockquote>
<p>Learning Objectives</p>
<ul>
<li>read textual data into R using <code>readtext</code></li>
<li>use <code>stringr</code> package to manipulate strings</li>
<li>use <code>tidytext</code> functions to tokenize texts and remove stopwords</li>
<li>use <code>SnowballC</code> to stem words</li>
</ul>
</blockquote>
<hr />
<p>We’ll use several libraries today. <code>sotu</code> will provide the metadata and text of State of the Union speeches ranging from George Washington to Barack Obama. <code>tidyverse</code> provides many of the standard “verbs” for working with our data. <code>tidytext</code> provides specific functions for a “tidy” approach to working with textual data. <code>readtext</code> provides a function well suited to reading textual data from a large number of formats into R.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(sotu)
<span class="kw">library</span>(tidyverse)
<span class="kw">library</span>(tidytext)
<span class="kw">library</span>(readtext)</code></pre>
<div id="reading-text-into-r" class="section level2">
<h2><span class="header-section-number">1.1</span> Reading text into R</h2>
<p>First, let’s look at the data in the <code>sotu</code> package. The metadata and texts come separately. We’ll use the supplied metadata object, but we’re going to use a utility function (<code>sotu_dir</code>) in the package to write the texts to disk so that we can practice reading text files from disk.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Let&#39;s take a quick look at the state of the union metadata</span>
<span class="kw">summary</span>(sotu_meta)</code></pre>
<pre><code>#&gt;   president              year      years_active          party          
#&gt;  Length:236         Min.   :1790   Length:236         Length:236        
#&gt;  Class :character   1st Qu.:1848   Class :character   Class :character  
#&gt;  Mode  :character   Median :1906   Mode  :character   Mode  :character  
#&gt;                     Mean   :1905                                        
#&gt;                     3rd Qu.:1962                                        
#&gt;                     Max.   :2016                                        
#&gt;   sotu_type        
#&gt;  Length:236        
#&gt;  Class :character  
#&gt;  Mode  :character  
#&gt;                    
#&gt;                    
#&gt; </code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># sotu_dir writes the text files to a temporary dir, but you could specific where you want them.</span>
fp &lt;-<span class="st"> </span><span class="kw">sotu_dir</span>()
<span class="kw">head</span>(fp)</code></pre>
<pre><code>#&gt; [1] &quot;/var/folders/5y/9x92pjcx2xd2h7qxqx39vpmc0000gn/T//Rtmp3Sozde/file11f05ea69b9/george-washington-1790a.txt&quot;
#&gt; [2] &quot;/var/folders/5y/9x92pjcx2xd2h7qxqx39vpmc0000gn/T//Rtmp3Sozde/file11f05ea69b9/george-washington-1790b.txt&quot;
#&gt; [3] &quot;/var/folders/5y/9x92pjcx2xd2h7qxqx39vpmc0000gn/T//Rtmp3Sozde/file11f05ea69b9/george-washington-1791.txt&quot; 
#&gt; [4] &quot;/var/folders/5y/9x92pjcx2xd2h7qxqx39vpmc0000gn/T//Rtmp3Sozde/file11f05ea69b9/george-washington-1792.txt&quot; 
#&gt; [5] &quot;/var/folders/5y/9x92pjcx2xd2h7qxqx39vpmc0000gn/T//Rtmp3Sozde/file11f05ea69b9/george-washington-1793.txt&quot; 
#&gt; [6] &quot;/var/folders/5y/9x92pjcx2xd2h7qxqx39vpmc0000gn/T//Rtmp3Sozde/file11f05ea69b9/george-washington-1794.txt&quot;</code></pre>
<p>Now that we have the files on disk, and a list of filepaths stored in the <code>fp</code> variable, we can use <code>readtext</code> to read the texts into a new variable.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># let&#39;s read in the files with readtext</span>
texts &lt;-<span class="st"> </span><span class="kw">readtext</span>(fp)
<span class="kw">head</span>(texts)</code></pre>
<pre><code>#&gt; readtext object consisting of 6 documents and 0 docvars.
#&gt; # Description: data.frame [6 × 2]
#&gt;   doc_id                   text                 
#&gt; * &lt;chr&gt;                    &lt;chr&gt;                
#&gt; 1 abraham-lincoln-1861.txt &quot;\&quot;\n\n Fellow-\&quot;...&quot;
#&gt; 2 abraham-lincoln-1862.txt &quot;\&quot;\n\n Fellow-\&quot;...&quot;
#&gt; 3 abraham-lincoln-1863.txt &quot;\&quot;\n\n Fellow-\&quot;...&quot;
#&gt; 4 abraham-lincoln-1864.txt &quot;\&quot;\n\n Fellow-\&quot;...&quot;
#&gt; 5 andrew-jackson-1829.txt  &quot;\&quot;\n\n Fellow \&quot;...&quot;
#&gt; 6 andrew-jackson-1830.txt  &quot;\&quot;\n\n Fellow \&quot;...&quot;</code></pre>
<p>So that we can work with a single tabular dataset with a tidy approach, we’ll convert the metadata and text tables to tibbles, and combine them into a single tibble. You can see that our texts are organized by alphabetical order, so first we’ll need to sort our metadata to match.</p>
<pre class="sourceCode r"><code class="sourceCode r">sotu_meta_tib &lt;-<span class="st"> </span><span class="kw">as_tibble</span>(sotu_meta) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">arrange</span>(president)

<span class="kw">head</span>(sotu_meta_tib)</code></pre>
<pre><code>#&gt; # A tibble: 6 x 5
#&gt;   president        year years_active party      sotu_type
#&gt;   &lt;chr&gt;           &lt;int&gt; &lt;chr&gt;        &lt;chr&gt;      &lt;chr&gt;    
#&gt; 1 Abraham Lincoln  1861 1861-1865    Republican written  
#&gt; 2 Abraham Lincoln  1862 1861-1865    Republican written  
#&gt; 3 Abraham Lincoln  1863 1861-1865    Republican written  
#&gt; 4 Abraham Lincoln  1864 1861-1865    Republican written  
#&gt; 5 Andrew Jackson   1829 1829-1833    Democratic written  
#&gt; 6 Andrew Jackson   1830 1829-1833    Democratic written</code></pre>
<p>We can now combine the sotu metadata with the texts. We’ll turn both pieces of data into tibbles, then combine.</p>
<pre class="sourceCode r"><code class="sourceCode r">sotu_texts &lt;-<span class="st"> </span><span class="kw">as_tibble</span>(texts)
sotu_whole &lt;-<span class="st"> </span><span class="kw">bind_cols</span>(sotu_meta_tib, sotu_texts)
<span class="kw">glimpse</span>(sotu_whole)</code></pre>
<pre><code>#&gt; Observations: 236
#&gt; Variables: 7
#&gt; $ president    &lt;chr&gt; &quot;Abraham Lincoln&quot;, &quot;Abraham Lincoln&quot;, &quot;Abraham Linc…
#&gt; $ year         &lt;int&gt; 1861, 1862, 1863, 1864, 1829, 1830, 1831, 1832, 183…
#&gt; $ years_active &lt;chr&gt; &quot;1861-1865&quot;, &quot;1861-1865&quot;, &quot;1861-1865&quot;, &quot;1861-1865&quot;,…
#&gt; $ party        &lt;chr&gt; &quot;Republican&quot;, &quot;Republican&quot;, &quot;Republican&quot;, &quot;Republic…
#&gt; $ sotu_type    &lt;chr&gt; &quot;written&quot;, &quot;written&quot;, &quot;written&quot;, &quot;written&quot;, &quot;writte…
#&gt; $ doc_id       &lt;chr&gt; &quot;abraham-lincoln-1861.txt&quot;, &quot;abraham-lincoln-1862.t…
#&gt; $ text         &lt;chr&gt; &quot;\n\n Fellow-Citizens of the Senate and House of Re…</code></pre>
<p>Now that we have our data, we need to think about cleaning it. Depending on the quality of your data, you might need to explicitly replace certain characters or words, remove urls or types of numbers, such as phone numbers, or otherwise clean up misspellings or errors. There are several ways to handle this sort of cleaning, but we’ll look at some straightforward string manipulation and replacement.</p>
</div>
<div id="string-operations" class="section level2">
<h2><span class="header-section-number">1.2</span> String operations</h2>
<p>R has many functions available to manipulate strings including functions like <code>grep</code> and <code>paste</code>, which come with the R base install.</p>
<p>Perhaps one of the most comprehensive packages is <code>stringi</code>. However, we will here take a look at the <code>stringr</code> package, which is part of the <code>tidyverse</code>, wraps a lot of the stringi functions, and is easier to begin with.</p>
<p>Below are examples for a few functions that might be useful.</p>
<ul>
<li>How many words in each speech?</li>
</ul>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">str_count</span>(sotu_whole<span class="op">$</span>text, <span class="kw">boundary</span>(<span class="st">&quot;word&quot;</span>))</code></pre>
<pre><code>#&gt;   [1]  6998  8410  6132  5975 10547 15109  7198  7887  7912 13472 10839
#&gt;  [12] 12386  9258  7155 12032  9886  6092  7263  6909  7058  6851  7064
#&gt;  [23]  6797  6078 13038 11559 16357 13718  6715  6978 10871 10333  8800
#&gt;  [34]  8083 13382 10315  8414  8956  6997  6027  7295  1090  8339  4166
#&gt;  [45]  4954  4995  5693  6260  2233  3536  3835  2743  4716  3785  3218
#&gt;  [56]  3332  3523  4618  3842  3162  8202  9613 10152 11626 10512  4824
#&gt;  [67]  3788  3964  5117  4380  3838  5390  5197  5071  5326  5571  5726
#&gt;  [78]  1091  1404  2305  2100  1969  2922  1988  2879  4153  4999  4747
#&gt;  [89] 19828 15196  5305 13275 12360 15972 14710 15568 27941  6090  5130
#&gt; [100]  3418  5154  4000  5387  9737 11051  4560  5705  4232 13685 16396
#&gt; [111] 12378 14085 16147 18251 16446 21366  1832  2448  2273  3248  3259
#&gt; [122]  2115  3145  3367  4423  4378  4709  3447  5831  4733  6383  8416
#&gt; [133]  4580 12155  3273 21588  3475 33537 33921  2062  2220  1507  1374
#&gt; [144]  5300  6637  5429  9027  7745  6996  7329  8254  8436  8047  9331
#&gt; [155]  3233  4453  5582  7221  4941  4137 11471 11520 13463  9007  8340
#&gt; [166] 13273  9951  4482  4532  3997 17383  5199 22419  4469  5182  5582
#&gt; [177]  4967  4235  3493  3814  4851 10755  7909 11670 13405 19708  9825
#&gt; [188] 15017 17517 25147 23680 27519 19515  3228  2203  2270  2100  2930
#&gt; [199]  2862  2387  2676  7720  8772  6480 10131 10058  9844 12238  6816
#&gt; [210]  5621  5774 13947 27696 23838 25275  7029  7423  9203  6357  6780
#&gt; [221]  7317  7513  9119 12157 20301 22907 19228  3566  4550  7735  2125
#&gt; [232]  3931  5482  4765  2714  7637</code></pre>
<ul>
<li>Measured by the average number of words per sentence for each speech - what is the length of the speech with the shortest/longest sentences?</li>
</ul>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">range</span>(<span class="kw">str_count</span>(sotu_whole<span class="op">$</span>text, <span class="kw">boundary</span>(<span class="st">&quot;word&quot;</span>))<span class="op">/</span><span class="kw">str_count</span>(sotu_whole<span class="op">$</span>text, <span class="kw">boundary</span>(<span class="st">&quot;sentence&quot;</span>)))</code></pre>
<pre><code>#&gt; [1]  9.143737 37.219008</code></pre>
<p>How man times does the word “citizen” appear in the speeches?</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">str_count</span>(sotu_whole<span class="op">$</span>text, <span class="st">&quot;[C|c]itizen&quot;</span>)</code></pre>
<pre><code>#&gt;   [1] 10  8 16  4 20 15 24 20 15 26 11 10 12 11 12 13  3  6  3  6  7  6  2
#&gt;  [24]  8 14 13 17 15 13  3  5  6  9  7 14  9 20 17 14 17 23  2  8  6  0  6
#&gt;  [47]  4  3  3  1  2  2  6  1  3  2  1  1  6  2  3 13 18 18 30  2  3  4  1
#&gt;  [70]  5  9 10  6  7  9 11 10  3  5  3  7  5 11  4  6  0  8  6 43 42  5 37
#&gt;  [93] 19 16 21 16  7  5 10  6  8  4  2 11  9  3  4  1 15 42 31 36 30 43 35
#&gt; [116] 16  4  4  5  5  5  3  4  6  8  9  7  4  7  2  8 10  4  9  3 15  4 24
#&gt; [139] 25  8  2  3  1  2  7  6 11  7 12  9 13 14 11  9  5  3  2  6  2  2 15
#&gt; [162] 28 18 14 15 17 15  0  0  0  8  2 10  2  4  3  4  5  2  3  0 16 18 28
#&gt; [185] 21 13  1 19 27 31 28 18 10 11  6  7  3  9  6  5  8 15 16 17 22 20 28
#&gt; [208] 29 22  4  5  9 10 10 27  1  2 22 12 11  9  3  8 20 12 26 13  4  2  8
#&gt; [231]  0  0  0  0  0 12</code></pre>
<p>What are the names of the documents where the word “citizen” does <strong>not</strong> occur?</p>
<pre class="sourceCode r"><code class="sourceCode r">sotu_whole<span class="op">$</span>doc_id[<span class="op">!</span><span class="kw">str_detect</span>(sotu_whole<span class="op">$</span>text, <span class="st">&quot;[C|c]itizen&quot;</span>)]</code></pre>
<pre><code>#&gt;  [1] &quot;dwight-d-eisenhower-1958.txt&quot; &quot;gerald-r-ford-1975.txt&quot;      
#&gt;  [3] &quot;richard-m-nixon-1970.txt&quot;     &quot;richard-m-nixon-1971.txt&quot;    
#&gt;  [5] &quot;richard-m-nixon-1972a.txt&quot;    &quot;ronald-reagan-1988.txt&quot;      
#&gt;  [7] &quot;woodrow-wilson-1916.txt&quot;      &quot;woodrow-wilson-1917.txt&quot;     
#&gt;  [9] &quot;woodrow-wilson-1918.txt&quot;      &quot;woodrow-wilson-1919.txt&quot;     
#&gt; [11] &quot;woodrow-wilson-1920.txt&quot;</code></pre>
<ul>
<li>Get me the first 5 words for each speech.</li>
</ul>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">word</span>(sotu_whole<span class="op">$</span>text, <span class="dt">end =</span> <span class="dv">5</span>) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">unique</span>()</code></pre>
<pre><code>#&gt;  [1] &quot;\n\n Fellow-Citizens of the Senate&quot;            
#&gt;  [2] &quot;\n\n Fellow Citizens of the&quot;                   
#&gt;  [3] &quot;Madam Speaker, Mr. Vice President,&quot;            
#&gt;  [4] &quot;Madam Speaker, Vice President Biden,&quot;          
#&gt;  [5] &quot;Mr. Speaker, Mr. Vice President,&quot;              
#&gt;  [6] &quot;Please, everybody, have a seat.&quot;               
#&gt;  [7] &quot;The President. Mr. Speaker, Mr.&quot;               
#&gt;  [8] &quot;Thank you. Mr. Speaker, Mr.&quot;                   
#&gt;  [9] &quot;\n\n To the Senate and&quot;                        
#&gt; [10] &quot;\n\nSince the close of the&quot;                    
#&gt; [11] &quot;\n\nTo the Congress of the&quot;                    
#&gt; [12] &quot;Members of the Congress: \n\nIn&quot;               
#&gt; [13] &quot;\n\nMembers of the Congress: \n\nIn&quot;           
#&gt; [14] &quot;\n\n Members of the Congress:&quot;                 
#&gt; [15] &quot;\n\n To the Congress of&quot;                       
#&gt; [16] &quot;Mr. President, Mr. Speaker, Members&quot;           
#&gt; [17] &quot;\n\n[Recorded on film and tape&quot;                
#&gt; [18] &quot;\n\n[Read before a joint session&quot;              
#&gt; [19] &quot;To the Congress of the&quot;                        
#&gt; [20] &quot;\n\n[Delivered in person before a&quot;             
#&gt; [21] &quot;Mr. President, Mr. Speaker, Senators&quot;          
#&gt; [22] &quot;Mr. Vice President, Mr. Speaker,&quot;              
#&gt; [23] &quot;IN FULFILLING my duty to&quot;                      
#&gt; [24] &quot;To the Congress: \n\nThis Nation&quot;              
#&gt; [25] &quot;\n\nToday, in pursuance of my&quot;                 
#&gt; [26] &quot;\n\nTo the Congress:\n\nIn considering the&quot;    
#&gt; [27] &quot;\n\nMr. Speaker, Mr. President, and&quot;           
#&gt; [28] &quot;\n\nMr. President, Mr. Speaker, Members&quot;       
#&gt; [29] &quot;\n\nMr. President and Mr. Speaker&quot;             
#&gt; [30] &quot;\n\nMr. Speaker and Mr. President,&quot;            
#&gt; [31] &quot;Thank you very much. Mr.&quot;                      
#&gt; [32] &quot;Mr. Speaker, Vice President Cheney,&quot;           
#&gt; [33] &quot;Thank you all. Mr. Speaker,&quot;                   
#&gt; [34] &quot;Thank you very much. And&quot;                      
#&gt; [35] &quot;Thank you all. Madam Speaker,&quot;                 
#&gt; [36] &quot;Fellow-Citizens of the Senate and&quot;             
#&gt; [37] &quot;\n\nFellow-Citizens of the Senate and&quot;         
#&gt; [38] &quot;\n\nMr. Speaker, Mr. Vice President,&quot;          
#&gt; [39] &quot;[Released January 21, 1946. Dated&quot;             
#&gt; [40] &quot;Mr. President, Mr. Speaker, and&quot;               
#&gt; [41] &quot;To the Senate and House&quot;                       
#&gt; [42] &quot;\n\nTo the Senate and House&quot;                   
#&gt; [43] &quot;\n\n Gentlemen of the Senate&quot;                  
#&gt; [44] &quot;\n\n[ As delivered in person&quot;                  
#&gt; [45] &quot;\n\n[As delivered in person before&quot;            
#&gt; [46] &quot;Mr. Speaker, Mr. President, Members&quot;           
#&gt; [47] &quot;\n\n[ Delivered in person before&quot;              
#&gt; [48] &quot;\n\nMr. Speaker, Mr. President, my&quot;            
#&gt; [49] &quot;Mr. Speaker, Mr. President, my&quot;                
#&gt; [50] &quot;Mr. Speaker, Mr. President, distinguished&quot;     
#&gt; [51] &quot;Mr. Speaker, Mr. President, and&quot;               
#&gt; [52] &quot;\n\n To The Senate and&quot;                        
#&gt; [53] &quot;\n\n The Senate and House&quot;                     
#&gt; [54] &quot;\n\nMR. SPEAKER AND MEMBERS OF&quot;                
#&gt; [55] &quot;\n\nMEMBERS OF THE CONGRESS: \n\nSo&quot;           
#&gt; [56] &quot;\n\nThe relations of the United&quot;               
#&gt; [57] &quot;\n\n Jump to Part II&quot;                          
#&gt; [58] &quot;\n\nGentlemen of the Congress:\n\nIn pursuance&quot;
#&gt; [59] &quot;\n\nGENTLEMEN OF THE CONGRESS: \n\nThe&quot;        
#&gt; [60] &quot;GENTLEMEN OF THE CONGRESS: \n\nSince&quot;          
#&gt; [61] &quot;\n\nGENTLEMEN OF THE CONGRESS: \n\nIn&quot;         
#&gt; [62] &quot;Gentlemen of the Congress:\n\nEight months&quot;    
#&gt; [63] &quot;\n\nTO THE SENATE AND HOUSE&quot;                   
#&gt; [64] &quot;\n\nGENTLEMEN OF THE CONGRESS:\n\nWhen I&quot;</code></pre>
<ul>
<li>Now remove the newline character (<code>\n</code>) and get rid of any leading white space:</li>
</ul>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">word</span>(sotu_whole<span class="op">$</span>text, <span class="dt">end =</span> <span class="dv">5</span>) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">unique</span>() <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">str_replace_all</span>(<span class="st">&quot;</span><span class="ch">\\</span><span class="st">n&quot;</span>, <span class="st">&quot; &quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">str_trim</span>()</code></pre>
<pre><code>#&gt;  [1] &quot;Fellow-Citizens of the Senate&quot;            
#&gt;  [2] &quot;Fellow Citizens of the&quot;                   
#&gt;  [3] &quot;Madam Speaker, Mr. Vice President,&quot;       
#&gt;  [4] &quot;Madam Speaker, Vice President Biden,&quot;     
#&gt;  [5] &quot;Mr. Speaker, Mr. Vice President,&quot;         
#&gt;  [6] &quot;Please, everybody, have a seat.&quot;          
#&gt;  [7] &quot;The President. Mr. Speaker, Mr.&quot;          
#&gt;  [8] &quot;Thank you. Mr. Speaker, Mr.&quot;              
#&gt;  [9] &quot;To the Senate and&quot;                        
#&gt; [10] &quot;Since the close of the&quot;                   
#&gt; [11] &quot;To the Congress of the&quot;                   
#&gt; [12] &quot;Members of the Congress:   In&quot;            
#&gt; [13] &quot;Members of the Congress:   In&quot;            
#&gt; [14] &quot;Members of the Congress:&quot;                 
#&gt; [15] &quot;To the Congress of&quot;                       
#&gt; [16] &quot;Mr. President, Mr. Speaker, Members&quot;      
#&gt; [17] &quot;[Recorded on film and tape&quot;               
#&gt; [18] &quot;[Read before a joint session&quot;             
#&gt; [19] &quot;To the Congress of the&quot;                   
#&gt; [20] &quot;[Delivered in person before a&quot;            
#&gt; [21] &quot;Mr. President, Mr. Speaker, Senators&quot;     
#&gt; [22] &quot;Mr. Vice President, Mr. Speaker,&quot;         
#&gt; [23] &quot;IN FULFILLING my duty to&quot;                 
#&gt; [24] &quot;To the Congress:   This Nation&quot;           
#&gt; [25] &quot;Today, in pursuance of my&quot;                
#&gt; [26] &quot;To the Congress:  In considering the&quot;     
#&gt; [27] &quot;Mr. Speaker, Mr. President, and&quot;          
#&gt; [28] &quot;Mr. President, Mr. Speaker, Members&quot;      
#&gt; [29] &quot;Mr. President and Mr. Speaker&quot;            
#&gt; [30] &quot;Mr. Speaker and Mr. President,&quot;           
#&gt; [31] &quot;Thank you very much. Mr.&quot;                 
#&gt; [32] &quot;Mr. Speaker, Vice President Cheney,&quot;      
#&gt; [33] &quot;Thank you all. Mr. Speaker,&quot;              
#&gt; [34] &quot;Thank you very much. And&quot;                 
#&gt; [35] &quot;Thank you all. Madam Speaker,&quot;            
#&gt; [36] &quot;Fellow-Citizens of the Senate and&quot;        
#&gt; [37] &quot;Fellow-Citizens of the Senate and&quot;        
#&gt; [38] &quot;Mr. Speaker, Mr. Vice President,&quot;         
#&gt; [39] &quot;[Released January 21, 1946. Dated&quot;        
#&gt; [40] &quot;Mr. President, Mr. Speaker, and&quot;          
#&gt; [41] &quot;To the Senate and House&quot;                  
#&gt; [42] &quot;To the Senate and House&quot;                  
#&gt; [43] &quot;Gentlemen of the Senate&quot;                  
#&gt; [44] &quot;[ As delivered in person&quot;                 
#&gt; [45] &quot;[As delivered in person before&quot;           
#&gt; [46] &quot;Mr. Speaker, Mr. President, Members&quot;      
#&gt; [47] &quot;[ Delivered in person before&quot;             
#&gt; [48] &quot;Mr. Speaker, Mr. President, my&quot;           
#&gt; [49] &quot;Mr. Speaker, Mr. President, my&quot;           
#&gt; [50] &quot;Mr. Speaker, Mr. President, distinguished&quot;
#&gt; [51] &quot;Mr. Speaker, Mr. President, and&quot;          
#&gt; [52] &quot;To The Senate and&quot;                        
#&gt; [53] &quot;The Senate and House&quot;                     
#&gt; [54] &quot;MR. SPEAKER AND MEMBERS OF&quot;               
#&gt; [55] &quot;MEMBERS OF THE CONGRESS:   So&quot;            
#&gt; [56] &quot;The relations of the United&quot;              
#&gt; [57] &quot;Jump to Part II&quot;                          
#&gt; [58] &quot;Gentlemen of the Congress:  In pursuance&quot; 
#&gt; [59] &quot;GENTLEMEN OF THE CONGRESS:   The&quot;         
#&gt; [60] &quot;GENTLEMEN OF THE CONGRESS:   Since&quot;       
#&gt; [61] &quot;GENTLEMEN OF THE CONGRESS:   In&quot;          
#&gt; [62] &quot;Gentlemen of the Congress:  Eight months&quot; 
#&gt; [63] &quot;TO THE SENATE AND HOUSE&quot;                  
#&gt; [64] &quot;GENTLEMEN OF THE CONGRESS:  When I&quot;</code></pre>
<p>(For spell checks take a look at <a href="https://CRAN.R-project.org/package=spelling" class="uri">https://CRAN.R-project.org/package=spelling</a> or <a href="https://CRAN.R-project.org/package=hunspell" class="uri">https://CRAN.R-project.org/package=hunspell</a>)</p>
</div>
<div id="tokenize-lowercase" class="section level2">
<h2><span class="header-section-number">1.3</span> Tokenize, lowercase</h2>
<p>A very common part of data cleaning involves tokenization. While our data is already “tidy” insofar as each row is a single observation, a single text with metdata, the tidytext approach goes a step further to make each word it’s own observation with metadata. We could write our own function to do this using a tokenizer, but <code>tidytext</code> provides a handy utility function just for this purpose.</p>
<pre class="sourceCode r"><code class="sourceCode r">tidy_sotu &lt;-<span class="st"> </span>sotu_whole <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">unnest_tokens</span>(word, text)

tidy_sotu</code></pre>
<pre><code>#&gt; # A tibble: 1,965,212 x 7
#&gt;    president     year years_active party   sotu_type doc_id        word    
#&gt;    &lt;chr&gt;        &lt;int&gt; &lt;chr&gt;        &lt;chr&gt;   &lt;chr&gt;     &lt;chr&gt;         &lt;chr&gt;   
#&gt;  1 Abraham Lin…  1861 1861-1865    Republ… written   abraham-linc… fellow  
#&gt;  2 Abraham Lin…  1861 1861-1865    Republ… written   abraham-linc… citizens
#&gt;  3 Abraham Lin…  1861 1861-1865    Republ… written   abraham-linc… of      
#&gt;  4 Abraham Lin…  1861 1861-1865    Republ… written   abraham-linc… the     
#&gt;  5 Abraham Lin…  1861 1861-1865    Republ… written   abraham-linc… senate  
#&gt;  6 Abraham Lin…  1861 1861-1865    Republ… written   abraham-linc… and     
#&gt;  7 Abraham Lin…  1861 1861-1865    Republ… written   abraham-linc… house   
#&gt;  8 Abraham Lin…  1861 1861-1865    Republ… written   abraham-linc… of      
#&gt;  9 Abraham Lin…  1861 1861-1865    Republ… written   abraham-linc… represe…
#&gt; 10 Abraham Lin…  1861 1861-1865    Republ… written   abraham-linc… in      
#&gt; # … with 1,965,202 more rows</code></pre>
<p>Before we move on, we should note that the <code>unnest_tokens</code> function didn’t just tokenize our texts at the word level. It also lowercased each word, and it could do quite a bit more. For instance, we could tokenize the text at the level of ngrams or sentences, if those are the best units of analysis for our work. We could also leave punctuation, which has been removed by default. Depending on what you need to do for analysis, you could do these operations during this step, or write custom functions and do it before you unnest tokens.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Word tokenization with punctuation</span>
tidy_sotu_w_punct &lt;-<span class="st"> </span>sotu_whole <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">unnest_tokens</span>(word, text, <span class="dt">strip_punct =</span> <span class="ot">FALSE</span>)

tidy_sotu_w_punct</code></pre>
<pre><code>#&gt; # A tibble: 2,157,777 x 7
#&gt;    president     year years_active party   sotu_type doc_id        word    
#&gt;    &lt;chr&gt;        &lt;int&gt; &lt;chr&gt;        &lt;chr&gt;   &lt;chr&gt;     &lt;chr&gt;         &lt;chr&gt;   
#&gt;  1 Abraham Lin…  1861 1861-1865    Republ… written   abraham-linc… fellow  
#&gt;  2 Abraham Lin…  1861 1861-1865    Republ… written   abraham-linc… -       
#&gt;  3 Abraham Lin…  1861 1861-1865    Republ… written   abraham-linc… citizens
#&gt;  4 Abraham Lin…  1861 1861-1865    Republ… written   abraham-linc… of      
#&gt;  5 Abraham Lin…  1861 1861-1865    Republ… written   abraham-linc… the     
#&gt;  6 Abraham Lin…  1861 1861-1865    Republ… written   abraham-linc… senate  
#&gt;  7 Abraham Lin…  1861 1861-1865    Republ… written   abraham-linc… and     
#&gt;  8 Abraham Lin…  1861 1861-1865    Republ… written   abraham-linc… house   
#&gt;  9 Abraham Lin…  1861 1861-1865    Republ… written   abraham-linc… of      
#&gt; 10 Abraham Lin…  1861 1861-1865    Republ… written   abraham-linc… represe…
#&gt; # … with 2,157,767 more rows</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Sentence tokenization</span>
tidy_sotu_sentences &lt;-<span class="st"> </span>sotu_whole <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">unnest_tokens</span>(sentence, text, <span class="dt">token =</span> <span class="st">&quot;sentences&quot;</span>, <span class="dt">to_lower =</span> <span class="ot">FALSE</span>)

tidy_sotu_sentences</code></pre>
<pre><code>#&gt; # A tibble: 69,158 x 7
#&gt;    president   year years_active party  sotu_type doc_id   sentence        
#&gt;    &lt;chr&gt;      &lt;int&gt; &lt;chr&gt;        &lt;chr&gt;  &lt;chr&gt;     &lt;chr&gt;    &lt;chr&gt;           
#&gt;  1 Abraham L…  1861 1861-1865    Repub… written   abraham… Fellow-Citizens…
#&gt;  2 Abraham L…  1861 1861-1865    Repub… written   abraham… You will not be…
#&gt;  3 Abraham L…  1861 1861-1865    Repub… written   abraham… A disloyal port…
#&gt;  4 Abraham L…  1861 1861-1865    Repub… written   abraham… A nation which …
#&gt;  5 Abraham L…  1861 1861-1865    Repub… written   abraham… Nations thus te…
#&gt;  6 Abraham L…  1861 1861-1865    Repub… written   abraham… The disloyal ci…
#&gt;  7 Abraham L…  1861 1861-1865    Repub… written   abraham… If it were just…
#&gt;  8 Abraham L…  1861 1861-1865    Repub… written   abraham… If we could dar…
#&gt;  9 Abraham L…  1861 1861-1865    Repub… written   abraham… The principal l…
#&gt; 10 Abraham L…  1861 1861-1865    Repub… written   abraham… Those nations, …
#&gt; # … with 69,148 more rows</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># N-gram tokenization</span>
tidy_sotu_trigram &lt;-<span class="st"> </span>sotu_whole <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">unnest_tokens</span>(trigram, text, <span class="dt">token =</span> <span class="st">&quot;ngrams&quot;</span>, <span class="dt">n =</span> <span class="dv">3</span>)

tidy_sotu_trigram</code></pre>
<pre><code>#&gt; # A tibble: 1,964,740 x 7
#&gt;    president    year years_active party   sotu_type doc_id      trigram    
#&gt;    &lt;chr&gt;       &lt;int&gt; &lt;chr&gt;        &lt;chr&gt;   &lt;chr&gt;     &lt;chr&gt;       &lt;chr&gt;      
#&gt;  1 Abraham Li…  1861 1861-1865    Republ… written   abraham-li… fellow cit…
#&gt;  2 Abraham Li…  1861 1861-1865    Republ… written   abraham-li… citizens o…
#&gt;  3 Abraham Li…  1861 1861-1865    Republ… written   abraham-li… of the sen…
#&gt;  4 Abraham Li…  1861 1861-1865    Republ… written   abraham-li… the senate…
#&gt;  5 Abraham Li…  1861 1861-1865    Republ… written   abraham-li… senate and…
#&gt;  6 Abraham Li…  1861 1861-1865    Republ… written   abraham-li… and house …
#&gt;  7 Abraham Li…  1861 1861-1865    Republ… written   abraham-li… house of r…
#&gt;  8 Abraham Li…  1861 1861-1865    Republ… written   abraham-li… of represe…
#&gt;  9 Abraham Li…  1861 1861-1865    Republ… written   abraham-li… representa…
#&gt; 10 Abraham Li…  1861 1861-1865    Republ… written   abraham-li… in the mid…
#&gt; # … with 1,964,730 more rows</code></pre>
</div>
<div id="stopwords" class="section level2">
<h2><span class="header-section-number">1.4</span> Stopwords</h2>
<p>Another common type of cleaning in text analysis is to remove stopwords, or common words that theoretically provide less information about the content of a text. Depending on the type of analysis you’re doing, you might leave these words in or use a highly curated list of stopwords. For now, as we move toward looking at words in documents based on frequency, we will remove some standard stopwords using a tidytext approach.</p>
<p>First, let’s look at the stopwords that tidytext gives us to get a sense of what they are.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">data</span>(stop_words)
<span class="kw">head</span>(stop_words, <span class="dt">n =</span> <span class="dv">60</span>)</code></pre>
<pre><code>#&gt; # A tibble: 60 x 2
#&gt;    word        lexicon
#&gt;    &lt;chr&gt;       &lt;chr&gt;  
#&gt;  1 a           SMART  
#&gt;  2 a&#39;s         SMART  
#&gt;  3 able        SMART  
#&gt;  4 about       SMART  
#&gt;  5 above       SMART  
#&gt;  6 according   SMART  
#&gt;  7 accordingly SMART  
#&gt;  8 across      SMART  
#&gt;  9 actually    SMART  
#&gt; 10 after       SMART  
#&gt; # … with 50 more rows</code></pre>
<p>You can see that we now have one word per row with associated metadata. We can now remove stopwords using an <code>anti-join</code>.</p>
<pre class="sourceCode r"><code class="sourceCode r">tidy_sotu_words &lt;-<span class="st"> </span>tidy_sotu <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">anti_join</span>(stop_words)

tidy_sotu_words</code></pre>
<pre><code>#&gt; # A tibble: 778,161 x 7
#&gt;    president     year years_active party   sotu_type doc_id        word    
#&gt;    &lt;chr&gt;        &lt;int&gt; &lt;chr&gt;        &lt;chr&gt;   &lt;chr&gt;     &lt;chr&gt;         &lt;chr&gt;   
#&gt;  1 Abraham Lin…  1861 1861-1865    Republ… written   abraham-linc… fellow  
#&gt;  2 Abraham Lin…  1861 1861-1865    Republ… written   abraham-linc… citizens
#&gt;  3 Abraham Lin…  1861 1861-1865    Republ… written   abraham-linc… senate  
#&gt;  4 Abraham Lin…  1861 1861-1865    Republ… written   abraham-linc… house   
#&gt;  5 Abraham Lin…  1861 1861-1865    Republ… written   abraham-linc… represe…
#&gt;  6 Abraham Lin…  1861 1861-1865    Republ… written   abraham-linc… midst   
#&gt;  7 Abraham Lin…  1861 1861-1865    Republ… written   abraham-linc… unprece…
#&gt;  8 Abraham Lin…  1861 1861-1865    Republ… written   abraham-linc… politic…
#&gt;  9 Abraham Lin…  1861 1861-1865    Republ… written   abraham-linc… troubles
#&gt; 10 Abraham Lin…  1861 1861-1865    Republ… written   abraham-linc… gratitu…
#&gt; # … with 778,151 more rows</code></pre>
<p>We went from 1965212 to 778161 rows, which means we had a lot of stopwords in our corpus. This is a huge removal, so for serious analysis, we might want to take a closer look at the stopwords and determine if we should use a different stopword list or otherwise create our own.</p>
</div>
<div id="word-stemming" class="section level2">
<h2><span class="header-section-number">1.5</span> Word Stemming</h2>
<p>Another thing you may want to do is to stem your words, that is, to reduce them to their word stem or root form, like reducing <em>fishing</em>, <em>fished</em>, and <em>fisher</em> to the stem <em>fish</em>.</p>
<p><code>tidytext</code> does not implement its own word stemmer. Instead it relies on separate packages like <code>hunspell</code> or <code>SnowballC</code>.</p>
<p>We will give an example here for the <code>SnowballC</code> package. (<code>hunspell</code> appears to run much slower, and it also returns a list instead of a vector, so in this context <code>SnowballC</code> seems to be more convenient.)</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(SnowballC)
tidy_sotu_words <span class="op">%&gt;%</span>
<span class="st">        </span><span class="kw">mutate</span>(<span class="dt">word_stem =</span> <span class="kw">wordStem</span>(word)) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">head</span>()</code></pre>
<pre><code>#&gt; # A tibble: 6 x 8
#&gt;   president   year years_active party  sotu_type doc_id    word   word_stem
#&gt;   &lt;chr&gt;      &lt;int&gt; &lt;chr&gt;        &lt;chr&gt;  &lt;chr&gt;     &lt;chr&gt;     &lt;chr&gt;  &lt;chr&gt;    
#&gt; 1 Abraham L…  1861 1861-1865    Repub… written   abraham-… fellow fellow   
#&gt; 2 Abraham L…  1861 1861-1865    Repub… written   abraham-… citiz… citizen  
#&gt; 3 Abraham L…  1861 1861-1865    Repub… written   abraham-… senate senat    
#&gt; 4 Abraham L…  1861 1861-1865    Repub… written   abraham-… house  hous     
#&gt; 5 Abraham L…  1861 1861-1865    Repub… written   abraham-… repre… repres   
#&gt; 6 Abraham L…  1861 1861-1865    Repub… written   abraham-… midst  midst</code></pre>
<p>For lemmatization, you may want to take a look a the <a href="https://CRAN.R-project.org/package=koRpus"><code>koRpus</code></a> package, another <a href="https://cran.r-project.org/web/packages/koRpus/vignettes/koRpus_vignette.html">comprehensive R package for text analysis</a>. It allows to use <a href="http://www.cis.uni-muenchen.de/~schmid/tools/TreeTagger/">TreeTagger</a>, a widely used part-of-speech tagger. For full functionality of the R package a local installation of TreeTagger is recommended.</p>
<p>Now that we’ve read in our text and metadata, reshaped it a bit into the tidytext format, and cleaned it a bit while doing so, let’s move on to some basic analysis.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="textanalysis.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/cengel/R-text-analysis/edit/master/01-data-prep.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"download": ["R-text-analysis.pdf", "R-text-analysis.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
